name: first-workflow
on:
  push:
    branches:
    - main
    
jobs:
  first-job-for-first-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: print-a-massage
        run: echo "wuba luba dup dup"
      - name: checkout-repo
        uses: actions/checkout@v6-beta
      - name: where-am-i
        run: |
          ls
          pwd
          whoami
          cat /etc/os-release
        