name: using-command-with-workflow
on:
  workflow_dispatch:
jobs:
  gob-1:
    runs-on: ubuntu-latest
    steps:
      - name: job1
        run: |
          depercated=true
          if [[ depercated ]]; then
            echo "::warning::Deprecated found"
          fi
      - name: gob-2
        run: echo "appkey=1234" >> $GITHUB_ENV
      - name: www
        run: echo "$appkey"
      - run: |
         if [-f "config.yml"]; then
           echo "::debug:: its exist"
         else
           echo "::error:: its not exists"
